// certifications.ts

export const certifications = [
  {
    icon: '🎓',
    title: 'Intro to LLMs',
    institute: 'IIT Madras',
    date: 'Apr 2025',
    logo: '/images/skills/nptel.png',
    skills: ['Prompt Engineering', 'Transformers', 'RAG'],
  },
  {
    icon: '🎓',
    title: 'Deep Learning for NLP',
    institute: 'IIT Kharagpur',
    date: 'Apr 2025',
    logo: '/images/skills/nptel.png',
    skills: ['NLP', 'LSTM', 'Transformers', 'Attention'],
  },
  {
    icon: '☁️',
    title: 'Cloud Foundations & Data Engineering',
    institute: 'AWS Academy',
    date: 'Feb 2025',
    logo: '/images/skills/aws.png',
    skills: ['AWS Basics', 'S3', 'Lambda', 'ETL Pipelines'],
  },
  {
    icon: '🧮',
    title: 'SQL Programming',
    institute: 'Oracle',
    date: 'Dec 2023',
    logo: '/images/skills/oracle.png',
    skills: ['SQL', 'Joins', 'Subqueries', 'PL/SQL'],
  },
  {
    icon: '💻',
    title: 'Front-End Development with JS',
    institute: 'TASK',
    date: 'Feb 2025',
    logo: '/logos/js.png',
    skills: ['JavaScript', 'DOM', 'Events', 'Forms'],
  },
  {
    icon: '✨',
    title: 'Soft Skills',
    institute: 'IIT Kharagpur (NPTEL)',
    date: 'Oct 2024',
    logo: '/images/skills/nptel.png',
    skills: ['Communication', 'Collaboration', 'Leadership'],
  },
  {
    icon: '🤖',
    title: 'Responsible AI',
    institute: 'IIITH (NPTEL)',
    date: 'Oct 2024',
    logo: '/images/skills/nptel.png',
    skills: ['Ethical AI', 'Bias', 'Fairness'],
  },
  {
    icon: '🔐',
    title: 'Privacy & Security for Online Social Media',
    institute: 'NPTEL',
    date: 'Apr 2024',
    logo: '/images/skills/nptel.png',
    skills: ['Privacy', 'Encryption', 'Security Protocols'],
  },
  {
    icon: '🐍',
    title: 'Joy of Computing with Python',
    institute: 'NPTEL',
    date: 'Oct 2023',
    logo: '/images/skills/nptel.png',
    skills: ['Python', 'Logic', 'Problem Solving'],
  },
  {
    icon: '📷',
    title: 'Computer Vision 101',
    institute: 'Infosys Springboard',
    date: 'Jan 2025',
    logo: '/images/skills/infosysspringboard.png',
    skills: ['Image Processing', 'OpenCV', 'Filters'],
  },
  {
    icon: '🤖',
    title: 'Introduction to RPA',
    institute: 'Springboard',
    date: 'Jan 2025',
    logo: '/images/skills/infosysspringboard.png',
    skills: ['Automation', 'Bots', 'Workflow Design'],
  },
]
